### ISSUE TITLE
[NumberGuesser] Минуты

### ISSUE THREAD

**Issue by pavel-b-novikov** [MillQK/nsudotnet#1]
А если я играл больше часа?

**Comment by MillQK** [comment]
Добавил отображение часов и секунд, думаю не целесообразно добавлять дни.

**Comment by pavel-b-novikov** [comment]
В задаче было написано - итоговое количество минут. Но черт с ним.

Неправильно ты, дядя Федор, часы и сеунды добавил. Через 3 аргумента сделал. А надо через один, манипулируя строкой формата.

**Comment by MillQK** [comment]
Исправил. Время теперь полностью в минутах, секунды отображаются как десятые доли минуты.

**Comment by pavel-b-novikov** [comment]
```timeDiff.Hours*60 + timeDiff.Minutes + timeDiff.Seconds/60.0```
Возможно, ваша бабушка бы и приняла такой код, и то - только потому что вы любимый внук. Я же скажу - вы видимо мой предыдущий комментарий вообще не прочитали.

**Comment by MillQK** [comment]
Я не очень понял, что вы имеете ввиду под манипуляцией строкой. Изменил, на то, что я думаю подойдет для исправления вашего замечания.

**Comment by pavel-b-novikov** [comment]
Я уже не знаю как понятнее-то объяснить - переделать строку формата для timeSpan-а так, чтобы она выводила часы, минуты, секунды. Ну.. ну правда я не знаю как понятнее объяснить.

**Comment by MillQK** [comment]
Походу до меня дошло. Изменил.

**Comment by pavel-b-novikov** [comment]
С чем я вас и поздравляю
