### ISSUE TITLE
[NumberGuesser] Exception-ы

### ISSUE THREAD

**Issue by pavel-b-novikov** [MillQK/nsudotnet#2]
А сделайте как-нибудь так парсеринг введенного числа, чтобы было без exception-ов. А то тяжеловато.

**Comment by MillQK** [comment]
Исправил, добавив метод проверки

**Comment by pavel-b-novikov** [comment]
Проверку на number сами написали? Слушайте, это шедевр индийского кода. Используйте готовый метод, который парсит без исключения.

**Comment by MillQK** [comment]
Исправил. Убрал свой шедевр подальше. Использую int.TryParse
