### ISSUE TITLE
[Enigma] Boolean

### ISSUE THREAD

**Issue by pavel-b-novikov** [MillQK/nsudotnet#4]
А чем отличается от bool?

**Comment by MillQK** [comment]
В данном случае ни чем, а в принципе обертка для типа bool, чтобы примитивный тип можно было считать объектом, и использовать в коллекциях и других местах, где требуются объекты.
Убрал boolean, сделал bool.

**Comment by pavel-b-novikov** [comment]
Чушь написали. Вопрос остается. Разбирайтесь дальше.

**Comment by MillQK** [comment]
Написал чушь, т.к. думал что в c# также, как и в java, каюсь.
Пишут, что bool это всего лишь псевдоним для Boolean.
Есть небольшая разница в написании, чтобы использовать Boolean нужно либо писать директиву  using System;, либо писать тип полностью System.Boolean, с bool такого делать не нужно.
По факту, это одно и тоже.
