### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [MillQK/nsudotnet#6]
Диспозится не всё. Найдите что не задиспожено и задиспозьте. Мне сюда отпишитесь

**Comment by MillQK** [comment]
SymmetricAlgorithm не диспозился. Исправил.

**Comment by pavel-b-novikov** [comment]
Нет, еще не все.

**Comment by MillQK** [comment]
ICryptoTransform еще. Исправил. Если есть еще что-то, я буду сильно удивлен.
